version: '2'
services:
  db:
    image: postgres
    ports:
      - "5433:5433"
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --verbosity=3"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .ENV
