# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(error_messages={'unique': 'A user with that email already exists.'}, max_length=280, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
            ],
            options={
                'db_table': 'skillsets',
                'verbose_name': 'skillset',
                'ordering': ('name',),
                'verbose_name_plural': 'skillsets',
            },
        ),
    ]
