# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 01:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 17, 1, 43, 10, 657739, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 17, 1, 43, 15, 9447, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
