# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='weight'),
        ),
    ]
