# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-11 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160910_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=280, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='years of experience'),
        ),
    ]
