# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-24 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161211_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, max_length=30, null=True, unique=True, verbose_name='username'),
        ),
    ]
