# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 00:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
        ('skillsets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(max_length=280)),
                ('description', models.TextField()),
                ('years_experience', models.IntegerField(default=0)),
                ('skills', models.ManyToManyField(to='skills.Skill')),
                ('skillsets', models.ManyToManyField(to='skillsets.Skillset')),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
