# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=280, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='years of experience'),
        ),
    ]
