# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='years_experience',
            field=models.IntegerField(blank=True, default=0, verbose_name='years of experience'),
        ),
    ]
