# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skillsets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=280)),
                ('description', models.TextField()),
                ('verified', models.BooleanField(default=False)),
                ('skillset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillsets.Skillset')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
    ]
