# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skillsets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=280, verbose_name='name')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='weight')),
                ('skillset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skillsets.Skillset', verbose_name='skillset')),
            ],
            options={
                'verbose_name': 'skill',
                'db_table': 'skills',
                'ordering': ('name',),
                'verbose_name_plural': 'skills',
            },
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('name', 'skillset')]),
        ),
    ]
