# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0002_skillset_weight'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skillset_id',
        ),
        migrations.AddField(
            model_name='skill',
            name='skillset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skillsets.Skillset', verbose_name='skillset'),
            preserve_default=False,
        ),
    ]
