# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=280, verbose_name='name'),
        ),
    ]
