# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillsets', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skillset_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skillsets.Skillset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
