# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 01:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20160616_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 17, 1, 43, 1, 810860, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 17, 1, 43, 6, 425989, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
