# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20160723_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(error_messages={'unique': 'A skill with that name already exists.'}, max_length=280, unique=True, verbose_name='name'),
        ),
    ]
