# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20160831_0337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('name', 'skillset')]),
        ),
    ]
